version: '3.8'

services:
  app:
    container_name: go_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SOURCE=postgresql://user:super-secret@go_db:5432/transaction-routines?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"
    command:
      ["/app/main"]

  db:
    container_name: go_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: super-secret
      POSTGRES_DB: transaction-routines
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: