version: '3.8'

services:
  app:
    container_name: go_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SOURCE=postgresql://${DB_USER}:${DB_PASSWORD}@go_db:${DB_PORT}/${DB_NAME}?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"
    command:
      ["/app/main"]

  db:
    container_name: go_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: