definitions:
  domain.Account:
    properties:
      documentNumber:
        type: string
      id:
        type: integer
    type: object
  request.AccountRequest:
    properties:
      document_number:
        type: string
    required:
    - document_number
    type: object
  request.Transaction:
    properties:
      account_id:
        type: integer
      amount:
        type: number
      operation_type:
        type: integer
    required:
    - account_id
    - amount
    - operation_type
    type: object
info:
  contact: {}
paths:
  /v1/account:
    post:
      consumes:
      - application/json
      description: Create an account for given document number for user.
      parameters:
      - description: AccountRequest
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create an account for user
  /v1/account/{accountId}:
    get:
      consumes:
      - application/json
      description: Create a transaction for given operation type with amount and account
        id
      parameters:
      - description: accountId
        in: path
        name: accountId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Initiate Transaction for a payment
  /v1/transaction:
    post:
      consumes:
      - application/json
      description: Create a transaction for given operation type with amount and account
        id
      parameters:
      - description: Transaction
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Transaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Initiate Transaction for a payment
swagger: "2.0"
